### ISSUE TITLE
Date error after using Extractor  ("Datum stellen")

### ISSUE THREAD

**Issue by Max11223344** [EliteAndroidApps/WhatsApp-Key-DB-Extractor#1]
Hello,
first let me thank you for the fantastic program.
It worked great, created all the files, but when i tried to restart Whatsapp afterwards it always started, then showed me a screen that my date was incorrect and a push key "Datum stellen" (set time) , which always leads to time settings. As my settings were correct i just confirmed the settings. But whatsapp remained in the state "Datum stellen" . In the topline of the screen there was a triangle with the exclamation mark saying Whatsapp error...
My Whatsapp-Version is 2.16.310 (german)
Android is 4.2
I overcame this problem with reinstalling Whatsapp from backup ....

**Comment by EliteAndroidApps** [comment]
Hi,
This usually happens when your current version of WhatsApp is not restored properly and the legacy version is left installed. Updating to the latest version manually will most certainly solve the issue. I'm still trying to figure why this occurs on occasion. Many thanks for your feedback and report. :)

**Comment by Max11223344** [comment]
Hi,
thanks for your speedy answer. 
As i said, i can live with it. I just reinstall the actual version ..

**Comment by EliteAndroidApps** [comment]
I will still look into it though and will leave the issue open in case anybody else has the same problem.
